# Generated by Django 5.1.1 on 2024-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_rating_delete_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.FloatField(),
        ),
    ]
