# Generated by Django 5.0 on 2024-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_alter_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='Site/static/avatars/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='path_to_img',
            field=models.ImageField(upload_to='Site/static/games/'),
        ),
    ]
