# Generated by Django 5.0 on 2024-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_account_avatar_alter_game_path_to_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='IGN',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_informer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='general_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='metacritic',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='path_to_img',
            field=models.ImageField(upload_to='games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_rate',
            field=models.FloatField(),
        ),
    ]
