# Generated by Django 5.0.4 on 2024-09-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_account_avatar_alter_game_ign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='metacritic',
            field=models.IntegerField(),
        ),
    ]
